### PR TITLE
Remove gdal optional dependency

### PR DESCRIPTION
**Pull request by ericpre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR removes `gdal` optional dependency.

### CODE REVIEW

**Comment by ericpre** [comment]
@conda-forge-admin, please rerender.

**Comment by Cadair** [comment]
Whats the reasoning behind this? I am rather out of touch with what the situation with gdal is. Maybe @quintusdias will be able to chime in.

**Comment by ericpre** [comment]
> Whats the reasoning behind this?

Simply avoid having to install all the dependencies required by gdal.

**Comment by quintusdias** [comment]
I can live with it.

**Comment by ericpre** [comment]
Thanks!

**Pull request merged**
